spring:
  application:
    name: oauth2-client
server:
  port: 9099
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
#security:
#  oauth2:
#    resource:
#      id: oauth2-client
#      user-info-uri: http://localhost:1202/auth/api/member#验证传入的令牌